[package]
name = "goauth"
version = "0.3.0"
authors = ["Drazen Urch <github@drazenur.ch>"]
description = "Crate for authenticating Server to Server Apps for Google Cloud Engine."
repository = "https://github.com/durch/rust-goauth"
readme = "README.md"
keywords = ["Google", "Cloud", "Engine", "Server", "OAuth"]
license = "MIT"
documentation = "https://durch.github.io/rust-goauth"

[lib]
name = "goauth"
path = "src/lib.rs"

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
time = "0.1.35"
curl = "0.4"
log = "0.3.6"
smpl_jwt = "0.2"
